# Generated by Django 5.1 on 2024-08-29 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0008_book_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'permissions': [('can_get_statistic', 'Can get genres statistic')]},
        ),
    ]
